#+title: macbookpro + ubuntu screen brightness
# H:2   controls section numbering.  
#       number top-level and second-level headings only
# ^:{}  require a_{b} before assuming that b should be subscripted.  
#       without this option a_b will automatically subscript b.
#+options: ^:{}
#
# options used exclusively by emacs
#+startup: showall
# 
# options used exclusively by the html exporter
#+language: en
#+infojs_opt: view:showall mouse:#ff8080 toc:nil ltoc:nil path:/ext/org/org-info.js
#+html_head: <link rel="stylesheet" type="text/css" href="css/notebook.css" />
#+html_link_home: index.html
#+html_link_up: index.html

* Introduction
  How-to for controlling screen brightness on a macbook pro under ubuntu.

  - source :: .org mode source for this page is here: file:mac-screen-brightness-src.org

* Procedure
  I installed ubuntu 15.10 (wily werewolf) on my late 2014 macbook pro (MacBookPro 11,3)
  I noticed I could no longer control screen brightness with F1/F2.
  I had previously made the following change when running ubuntu 14.04:
  #+begin_example
  add to /etc/rc.local:
  setpci -v -H1 -s 00:01.00 BRIDGE_CONTROL=0
  #+end_example
  After upgrading to 15.10,  ~/etc/rc.local~ still has this change.
  
  After some digging,  thanks to this link.
  - https://help.ubuntu.com/community/MacBook%20Aluminum,
  I found that the following worked:
  
  #+begin_example
  # make screen quite dim..
  echo 100 | sudo tee -a /sys/class/backlight/gmux_backlight/brightness
  # make screen quite bright..
  echo 800 | sudo tee -a /sys/class/backlight/gmux_backlight/brightness
  #+end_example
